# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Form
version:      00.03
version_from: Form.pm
installdirs:  site
requires:
    Class::DBI::Plugin::Type:      0
    HTML::Tag:                     0
    Tie::IxHash:                   0
    URI::Escape:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
